// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: big_integer.proto

package com.dsumtsov.mapstruct.protobuf.demo.protobuf;

public final class BIntegerProto {
  private BIntegerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BIntegerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BInteger)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string val = 1;</code>
     * @return The val.
     */
    java.lang.String getVal();
    /**
     * <code>string val = 1;</code>
     * @return The bytes for val.
     */
    com.google.protobuf.ByteString
        getValBytes();
  }
  /**
   * Protobuf type {@code BInteger}
   */
  public  static final class BInteger extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BInteger)
      BIntegerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BInteger.newBuilder() to construct.
    private BInteger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BInteger() {
      val_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BInteger();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BInteger(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              val_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.internal_static_BInteger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.internal_static_BInteger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.class, com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.Builder.class);
    }

    public static final int VAL_FIELD_NUMBER = 1;
    private volatile java.lang.Object val_;
    /**
     * <code>string val = 1;</code>
     * @return The val.
     */
    public java.lang.String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        val_ = s;
        return s;
      }
    }
    /**
     * <code>string val = 1;</code>
     * @return The bytes for val.
     */
    public com.google.protobuf.ByteString
        getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, val_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, val_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger other = (com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger) obj;

      if (!getVal()
          .equals(other.getVal())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VAL_FIELD_NUMBER;
      hash = (53 * hash) + getVal().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BInteger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BInteger)
        com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BIntegerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.internal_static_BInteger_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.internal_static_BInteger_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.class, com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        val_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.internal_static_BInteger_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger build() {
        com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger buildPartial() {
        com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger result = new com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger(this);
        result.val_ = val_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger other) {
        if (other == com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger.getDefaultInstance()) return this;
        if (!other.getVal().isEmpty()) {
          val_ = other.val_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object val_ = "";
      /**
       * <code>string val = 1;</code>
       * @return The val.
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          val_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string val = 1;</code>
       * @return The bytes for val.
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string val = 1;</code>
       * @param value The val to set.
       * @return This builder for chaining.
       */
      public Builder setVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string val = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVal() {
        
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      /**
       * <code>string val = 1;</code>
       * @param value The bytes for val to set.
       * @return This builder for chaining.
       */
      public Builder setValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        val_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BInteger)
    }

    // @@protoc_insertion_point(class_scope:BInteger)
    private static final com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger();
    }

    public static com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BInteger>
        PARSER = new com.google.protobuf.AbstractParser<BInteger>() {
      @java.lang.Override
      public BInteger parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BInteger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BInteger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BInteger> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.demo.protobuf.BIntegerProto.BInteger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BInteger_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BInteger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021big_integer.proto\"\027\n\010BInteger\022\013\n\003val\030\001" +
      " \001(\tB>\n-com.dsumtsov.mapstruct.protobuf." +
      "demo.protobufB\rBIntegerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BInteger_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BInteger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BInteger_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
