// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: big_decimal.proto

package com.dsumtsov.mapstruct.protobuf.example.protobuf;

public final class BDecimalProto {
  private BDecimalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BDecimalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BDecimal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 scale = 1;</code>
     * @return The scale.
     */
    int getScale();

    /**
     * <code>.BInteger int_val = 2;</code>
     * @return Whether the intVal field is set.
     */
    boolean hasIntVal();
    /**
     * <code>.BInteger int_val = 2;</code>
     * @return The intVal.
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger getIntVal();
    /**
     * <code>.BInteger int_val = 2;</code>
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder getIntValOrBuilder();
  }
  /**
   * Protobuf type {@code BDecimal}
   */
  public  static final class BDecimal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BDecimal)
      BDecimalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BDecimal.newBuilder() to construct.
    private BDecimal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BDecimal() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BDecimal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BDecimal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              scale_ = input.readInt32();
              break;
            }
            case 18: {
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder subBuilder = null;
              if (intVal_ != null) {
                subBuilder = intVal_.toBuilder();
              }
              intVal_ = input.readMessage(com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(intVal_);
                intVal_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.internal_static_BDecimal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.internal_static_BDecimal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder.class);
    }

    public static final int SCALE_FIELD_NUMBER = 1;
    private int scale_;
    /**
     * <code>int32 scale = 1;</code>
     * @return The scale.
     */
    public int getScale() {
      return scale_;
    }

    public static final int INT_VAL_FIELD_NUMBER = 2;
    private com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger intVal_;
    /**
     * <code>.BInteger int_val = 2;</code>
     * @return Whether the intVal field is set.
     */
    public boolean hasIntVal() {
      return intVal_ != null;
    }
    /**
     * <code>.BInteger int_val = 2;</code>
     * @return The intVal.
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger getIntVal() {
      return intVal_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.getDefaultInstance() : intVal_;
    }
    /**
     * <code>.BInteger int_val = 2;</code>
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder getIntValOrBuilder() {
      return getIntVal();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (scale_ != 0) {
        output.writeInt32(1, scale_);
      }
      if (intVal_ != null) {
        output.writeMessage(2, getIntVal());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (scale_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, scale_);
      }
      if (intVal_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIntVal());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal other = (com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal) obj;

      if (getScale()
          != other.getScale()) return false;
      if (hasIntVal() != other.hasIntVal()) return false;
      if (hasIntVal()) {
        if (!getIntVal()
            .equals(other.getIntVal())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCALE_FIELD_NUMBER;
      hash = (53 * hash) + getScale();
      if (hasIntVal()) {
        hash = (37 * hash) + INT_VAL_FIELD_NUMBER;
        hash = (53 * hash) + getIntVal().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BDecimal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BDecimal)
        com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.internal_static_BDecimal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.internal_static_BDecimal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        scale_ = 0;

        if (intValBuilder_ == null) {
          intVal_ = null;
        } else {
          intVal_ = null;
          intValBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.internal_static_BDecimal_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal build() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal buildPartial() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal result = new com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal(this);
        result.scale_ = scale_;
        if (intValBuilder_ == null) {
          result.intVal_ = intVal_;
        } else {
          result.intVal_ = intValBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal other) {
        if (other == com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.getDefaultInstance()) return this;
        if (other.getScale() != 0) {
          setScale(other.getScale());
        }
        if (other.hasIntVal()) {
          mergeIntVal(other.getIntVal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int scale_ ;
      /**
       * <code>int32 scale = 1;</code>
       * @return The scale.
       */
      public int getScale() {
        return scale_;
      }
      /**
       * <code>int32 scale = 1;</code>
       * @param value The scale to set.
       * @return This builder for chaining.
       */
      public Builder setScale(int value) {
        
        scale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 scale = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScale() {
        
        scale_ = 0;
        onChanged();
        return this;
      }

      private com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger intVal_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder> intValBuilder_;
      /**
       * <code>.BInteger int_val = 2;</code>
       * @return Whether the intVal field is set.
       */
      public boolean hasIntVal() {
        return intValBuilder_ != null || intVal_ != null;
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       * @return The intVal.
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger getIntVal() {
        if (intValBuilder_ == null) {
          return intVal_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.getDefaultInstance() : intVal_;
        } else {
          return intValBuilder_.getMessage();
        }
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public Builder setIntVal(com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger value) {
        if (intValBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          intVal_ = value;
          onChanged();
        } else {
          intValBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public Builder setIntVal(
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder builderForValue) {
        if (intValBuilder_ == null) {
          intVal_ = builderForValue.build();
          onChanged();
        } else {
          intValBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public Builder mergeIntVal(com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger value) {
        if (intValBuilder_ == null) {
          if (intVal_ != null) {
            intVal_ =
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.newBuilder(intVal_).mergeFrom(value).buildPartial();
          } else {
            intVal_ = value;
          }
          onChanged();
        } else {
          intValBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public Builder clearIntVal() {
        if (intValBuilder_ == null) {
          intVal_ = null;
          onChanged();
        } else {
          intVal_ = null;
          intValBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder getIntValBuilder() {
        
        onChanged();
        return getIntValFieldBuilder().getBuilder();
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder getIntValOrBuilder() {
        if (intValBuilder_ != null) {
          return intValBuilder_.getMessageOrBuilder();
        } else {
          return intVal_ == null ?
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.getDefaultInstance() : intVal_;
        }
      }
      /**
       * <code>.BInteger int_val = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder> 
          getIntValFieldBuilder() {
        if (intValBuilder_ == null) {
          intValBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BInteger.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.BIntegerOrBuilder>(
                  getIntVal(),
                  getParentForChildren(),
                  isClean());
          intVal_ = null;
        }
        return intValBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BDecimal)
    }

    // @@protoc_insertion_point(class_scope:BDecimal)
    private static final com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal();
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BDecimal>
        PARSER = new com.google.protobuf.AbstractParser<BDecimal>() {
      @java.lang.Override
      public BDecimal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BDecimal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BDecimal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BDecimal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BDecimal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BDecimal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021big_decimal.proto\032\021big_integer.proto\"5" +
      "\n\010BDecimal\022\r\n\005scale\030\001 \001(\005\022\032\n\007int_val\030\002 \001" +
      "(\0132\t.BIntegerBA\n0com.dsumtsov.mapstruct." +
      "protobuf.example.protobufB\rBDecimalProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.getDescriptor(),
        });
    internal_static_BDecimal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BDecimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BDecimal_descriptor,
        new java.lang.String[] { "Scale", "IntVal", });
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BIntegerProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
