// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange_rate.proto

package com.dsumtsov.mapstruct.protobuf.example.protobuf;

public final class ExchangeRateProto {
  private ExchangeRateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeRateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExchangeRate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string basic_currency = 1;</code>
     * @return The basicCurrency.
     */
    java.lang.String getBasicCurrency();
    /**
     * <code>string basic_currency = 1;</code>
     * @return The bytes for basicCurrency.
     */
    com.google.protobuf.ByteString
        getBasicCurrencyBytes();

    /**
     * <code>string target_currency = 2;</code>
     * @return The targetCurrency.
     */
    java.lang.String getTargetCurrency();
    /**
     * <code>string target_currency = 2;</code>
     * @return The bytes for targetCurrency.
     */
    com.google.protobuf.ByteString
        getTargetCurrencyBytes();

    /**
     * <code>.BDecimal rate = 3;</code>
     * @return Whether the rate field is set.
     */
    boolean hasRate();
    /**
     * <code>.BDecimal rate = 3;</code>
     * @return The rate.
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getRate();
    /**
     * <code>.BDecimal rate = 3;</code>
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder getRateOrBuilder();
  }
  /**
   * Protobuf type {@code ExchangeRate}
   */
  public  static final class ExchangeRate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExchangeRate)
      ExchangeRateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRate.newBuilder() to construct.
    private ExchangeRate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRate() {
      basicCurrency_ = "";
      targetCurrency_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExchangeRate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              basicCurrency_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              targetCurrency_ = s;
              break;
            }
            case 26: {
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder subBuilder = null;
              if (rate_ != null) {
                subBuilder = rate_.toBuilder();
              }
              rate_ = input.readMessage(com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rate_);
                rate_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder.class);
    }

    public static final int BASIC_CURRENCY_FIELD_NUMBER = 1;
    private volatile java.lang.Object basicCurrency_;
    /**
     * <code>string basic_currency = 1;</code>
     * @return The basicCurrency.
     */
    public java.lang.String getBasicCurrency() {
      java.lang.Object ref = basicCurrency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basicCurrency_ = s;
        return s;
      }
    }
    /**
     * <code>string basic_currency = 1;</code>
     * @return The bytes for basicCurrency.
     */
    public com.google.protobuf.ByteString
        getBasicCurrencyBytes() {
      java.lang.Object ref = basicCurrency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basicCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_CURRENCY_FIELD_NUMBER = 2;
    private volatile java.lang.Object targetCurrency_;
    /**
     * <code>string target_currency = 2;</code>
     * @return The targetCurrency.
     */
    public java.lang.String getTargetCurrency() {
      java.lang.Object ref = targetCurrency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetCurrency_ = s;
        return s;
      }
    }
    /**
     * <code>string target_currency = 2;</code>
     * @return The bytes for targetCurrency.
     */
    public com.google.protobuf.ByteString
        getTargetCurrencyBytes() {
      java.lang.Object ref = targetCurrency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATE_FIELD_NUMBER = 3;
    private com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal rate_;
    /**
     * <code>.BDecimal rate = 3;</code>
     * @return Whether the rate field is set.
     */
    public boolean hasRate() {
      return rate_ != null;
    }
    /**
     * <code>.BDecimal rate = 3;</code>
     * @return The rate.
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getRate() {
      return rate_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.getDefaultInstance() : rate_;
    }
    /**
     * <code>.BDecimal rate = 3;</code>
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder getRateOrBuilder() {
      return getRate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBasicCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, basicCurrency_);
      }
      if (!getTargetCurrencyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, targetCurrency_);
      }
      if (rate_ != null) {
        output.writeMessage(3, getRate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBasicCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, basicCurrency_);
      }
      if (!getTargetCurrencyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, targetCurrency_);
      }
      if (rate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate other = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate) obj;

      if (!getBasicCurrency()
          .equals(other.getBasicCurrency())) return false;
      if (!getTargetCurrency()
          .equals(other.getTargetCurrency())) return false;
      if (hasRate() != other.hasRate()) return false;
      if (hasRate()) {
        if (!getRate()
            .equals(other.getRate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BASIC_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getBasicCurrency().hashCode();
      hash = (37 * hash) + TARGET_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getTargetCurrency().hashCode();
      if (hasRate()) {
        hash = (37 * hash) + RATE_FIELD_NUMBER;
        hash = (53 * hash) + getRate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExchangeRate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExchangeRate)
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        basicCurrency_ = "";

        targetCurrency_ = "";

        if (rateBuilder_ == null) {
          rate_ = null;
        } else {
          rate_ = null;
          rateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRate_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate build() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate buildPartial() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate result = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate(this);
        result.basicCurrency_ = basicCurrency_;
        result.targetCurrency_ = targetCurrency_;
        if (rateBuilder_ == null) {
          result.rate_ = rate_;
        } else {
          result.rate_ = rateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate other) {
        if (other == com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.getDefaultInstance()) return this;
        if (!other.getBasicCurrency().isEmpty()) {
          basicCurrency_ = other.basicCurrency_;
          onChanged();
        }
        if (!other.getTargetCurrency().isEmpty()) {
          targetCurrency_ = other.targetCurrency_;
          onChanged();
        }
        if (other.hasRate()) {
          mergeRate(other.getRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object basicCurrency_ = "";
      /**
       * <code>string basic_currency = 1;</code>
       * @return The basicCurrency.
       */
      public java.lang.String getBasicCurrency() {
        java.lang.Object ref = basicCurrency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          basicCurrency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string basic_currency = 1;</code>
       * @return The bytes for basicCurrency.
       */
      public com.google.protobuf.ByteString
          getBasicCurrencyBytes() {
        java.lang.Object ref = basicCurrency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          basicCurrency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string basic_currency = 1;</code>
       * @param value The basicCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setBasicCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        basicCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string basic_currency = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBasicCurrency() {
        
        basicCurrency_ = getDefaultInstance().getBasicCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string basic_currency = 1;</code>
       * @param value The bytes for basicCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setBasicCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        basicCurrency_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetCurrency_ = "";
      /**
       * <code>string target_currency = 2;</code>
       * @return The targetCurrency.
       */
      public java.lang.String getTargetCurrency() {
        java.lang.Object ref = targetCurrency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetCurrency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target_currency = 2;</code>
       * @return The bytes for targetCurrency.
       */
      public com.google.protobuf.ByteString
          getTargetCurrencyBytes() {
        java.lang.Object ref = targetCurrency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetCurrency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target_currency = 2;</code>
       * @param value The targetCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setTargetCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetCurrency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string target_currency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetCurrency() {
        
        targetCurrency_ = getDefaultInstance().getTargetCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>string target_currency = 2;</code>
       * @param value The bytes for targetCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setTargetCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetCurrency_ = value;
        onChanged();
        return this;
      }

      private com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal rate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder> rateBuilder_;
      /**
       * <code>.BDecimal rate = 3;</code>
       * @return Whether the rate field is set.
       */
      public boolean hasRate() {
        return rateBuilder_ != null || rate_ != null;
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       * @return The rate.
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal getRate() {
        if (rateBuilder_ == null) {
          return rate_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.getDefaultInstance() : rate_;
        } else {
          return rateBuilder_.getMessage();
        }
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public Builder setRate(com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal value) {
        if (rateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rate_ = value;
          onChanged();
        } else {
          rateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public Builder setRate(
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder builderForValue) {
        if (rateBuilder_ == null) {
          rate_ = builderForValue.build();
          onChanged();
        } else {
          rateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public Builder mergeRate(com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal value) {
        if (rateBuilder_ == null) {
          if (rate_ != null) {
            rate_ =
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.newBuilder(rate_).mergeFrom(value).buildPartial();
          } else {
            rate_ = value;
          }
          onChanged();
        } else {
          rateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public Builder clearRate() {
        if (rateBuilder_ == null) {
          rate_ = null;
          onChanged();
        } else {
          rate_ = null;
          rateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder getRateBuilder() {
        
        onChanged();
        return getRateFieldBuilder().getBuilder();
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder getRateOrBuilder() {
        if (rateBuilder_ != null) {
          return rateBuilder_.getMessageOrBuilder();
        } else {
          return rate_ == null ?
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.getDefaultInstance() : rate_;
        }
      }
      /**
       * <code>.BDecimal rate = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder> 
          getRateFieldBuilder() {
        if (rateBuilder_ == null) {
          rateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimal.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.BDecimalOrBuilder>(
                  getRate(),
                  getParentForChildren(),
                  isClean());
          rate_ = null;
        }
        return rateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExchangeRate)
    }

    // @@protoc_insertion_point(class_scope:ExchangeRate)
    private static final com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate();
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRate>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRate>() {
      @java.lang.Override
      public ExchangeRate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExchangeRateListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExchangeRateList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> 
        getExchangeRateList();
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getExchangeRate(int index);
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    int getExchangeRateCount();
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    java.util.List<? extends com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder> 
        getExchangeRateOrBuilderList();
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder getExchangeRateOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ExchangeRateList}
   */
  public  static final class ExchangeRateList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExchangeRateList)
      ExchangeRateListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExchangeRateList.newBuilder() to construct.
    private ExchangeRateList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeRateList() {
      exchangeRate_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExchangeRateList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExchangeRateList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                exchangeRate_ = new java.util.ArrayList<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate>();
                mutable_bitField0_ |= 0x00000001;
              }
              exchangeRate_.add(
                  input.readMessage(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          exchangeRate_ = java.util.Collections.unmodifiableList(exchangeRate_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRateList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRateList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.Builder.class);
    }

    public static final int EXCHANGE_RATE_FIELD_NUMBER = 1;
    private java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> exchangeRate_;
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    public java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> getExchangeRateList() {
      return exchangeRate_;
    }
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    public java.util.List<? extends com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder> 
        getExchangeRateOrBuilderList() {
      return exchangeRate_;
    }
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    public int getExchangeRateCount() {
      return exchangeRate_.size();
    }
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getExchangeRate(int index) {
      return exchangeRate_.get(index);
    }
    /**
     * <code>repeated .ExchangeRate exchange_rate = 1;</code>
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder getExchangeRateOrBuilder(
        int index) {
      return exchangeRate_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < exchangeRate_.size(); i++) {
        output.writeMessage(1, exchangeRate_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < exchangeRate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, exchangeRate_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList other = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList) obj;

      if (!getExchangeRateList()
          .equals(other.getExchangeRateList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getExchangeRateCount() > 0) {
        hash = (37 * hash) + EXCHANGE_RATE_FIELD_NUMBER;
        hash = (53 * hash) + getExchangeRateList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExchangeRateList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExchangeRateList)
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRateList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRateList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExchangeRateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (exchangeRateBuilder_ == null) {
          exchangeRate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          exchangeRateBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.internal_static_ExchangeRateList_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList build() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList buildPartial() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList result = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList(this);
        int from_bitField0_ = bitField0_;
        if (exchangeRateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            exchangeRate_ = java.util.Collections.unmodifiableList(exchangeRate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.exchangeRate_ = exchangeRate_;
        } else {
          result.exchangeRate_ = exchangeRateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList other) {
        if (other == com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList.getDefaultInstance()) return this;
        if (exchangeRateBuilder_ == null) {
          if (!other.exchangeRate_.isEmpty()) {
            if (exchangeRate_.isEmpty()) {
              exchangeRate_ = other.exchangeRate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExchangeRateIsMutable();
              exchangeRate_.addAll(other.exchangeRate_);
            }
            onChanged();
          }
        } else {
          if (!other.exchangeRate_.isEmpty()) {
            if (exchangeRateBuilder_.isEmpty()) {
              exchangeRateBuilder_.dispose();
              exchangeRateBuilder_ = null;
              exchangeRate_ = other.exchangeRate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              exchangeRateBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExchangeRateFieldBuilder() : null;
            } else {
              exchangeRateBuilder_.addAllMessages(other.exchangeRate_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> exchangeRate_ =
        java.util.Collections.emptyList();
      private void ensureExchangeRateIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          exchangeRate_ = new java.util.ArrayList<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate>(exchangeRate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder> exchangeRateBuilder_;

      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> getExchangeRateList() {
        if (exchangeRateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exchangeRate_);
        } else {
          return exchangeRateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public int getExchangeRateCount() {
        if (exchangeRateBuilder_ == null) {
          return exchangeRate_.size();
        } else {
          return exchangeRateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate getExchangeRate(int index) {
        if (exchangeRateBuilder_ == null) {
          return exchangeRate_.get(index);
        } else {
          return exchangeRateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder setExchangeRate(
          int index, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate value) {
        if (exchangeRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeRateIsMutable();
          exchangeRate_.set(index, value);
          onChanged();
        } else {
          exchangeRateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder setExchangeRate(
          int index, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder builderForValue) {
        if (exchangeRateBuilder_ == null) {
          ensureExchangeRateIsMutable();
          exchangeRate_.set(index, builderForValue.build());
          onChanged();
        } else {
          exchangeRateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder addExchangeRate(com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate value) {
        if (exchangeRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeRateIsMutable();
          exchangeRate_.add(value);
          onChanged();
        } else {
          exchangeRateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder addExchangeRate(
          int index, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate value) {
        if (exchangeRateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExchangeRateIsMutable();
          exchangeRate_.add(index, value);
          onChanged();
        } else {
          exchangeRateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder addExchangeRate(
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder builderForValue) {
        if (exchangeRateBuilder_ == null) {
          ensureExchangeRateIsMutable();
          exchangeRate_.add(builderForValue.build());
          onChanged();
        } else {
          exchangeRateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder addExchangeRate(
          int index, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder builderForValue) {
        if (exchangeRateBuilder_ == null) {
          ensureExchangeRateIsMutable();
          exchangeRate_.add(index, builderForValue.build());
          onChanged();
        } else {
          exchangeRateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder addAllExchangeRate(
          java.lang.Iterable<? extends com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate> values) {
        if (exchangeRateBuilder_ == null) {
          ensureExchangeRateIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exchangeRate_);
          onChanged();
        } else {
          exchangeRateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder clearExchangeRate() {
        if (exchangeRateBuilder_ == null) {
          exchangeRate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          exchangeRateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public Builder removeExchangeRate(int index) {
        if (exchangeRateBuilder_ == null) {
          ensureExchangeRateIsMutable();
          exchangeRate_.remove(index);
          onChanged();
        } else {
          exchangeRateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder getExchangeRateBuilder(
          int index) {
        return getExchangeRateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder getExchangeRateOrBuilder(
          int index) {
        if (exchangeRateBuilder_ == null) {
          return exchangeRate_.get(index);  } else {
          return exchangeRateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public java.util.List<? extends com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder> 
           getExchangeRateOrBuilderList() {
        if (exchangeRateBuilder_ != null) {
          return exchangeRateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exchangeRate_);
        }
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder addExchangeRateBuilder() {
        return getExchangeRateFieldBuilder().addBuilder(
            com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.getDefaultInstance());
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder addExchangeRateBuilder(
          int index) {
        return getExchangeRateFieldBuilder().addBuilder(
            index, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.getDefaultInstance());
      }
      /**
       * <code>repeated .ExchangeRate exchange_rate = 1;</code>
       */
      public java.util.List<com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder> 
           getExchangeRateBuilderList() {
        return getExchangeRateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder> 
          getExchangeRateFieldBuilder() {
        if (exchangeRateBuilder_ == null) {
          exchangeRateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRate.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateOrBuilder>(
                  exchangeRate_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          exchangeRate_ = null;
        }
        return exchangeRateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExchangeRateList)
    }

    // @@protoc_insertion_point(class_scope:ExchangeRateList)
    private static final com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList();
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeRateList>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeRateList>() {
      @java.lang.Override
      public ExchangeRateList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExchangeRateList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeRateList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeRateList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ExchangeRateProto.ExchangeRateList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExchangeRate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExchangeRate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExchangeRateList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExchangeRateList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023exchange_rate.proto\032\021big_decimal.proto" +
      "\"X\n\014ExchangeRate\022\026\n\016basic_currency\030\001 \001(\t" +
      "\022\027\n\017target_currency\030\002 \001(\t\022\027\n\004rate\030\003 \001(\0132" +
      "\t.BDecimal\"8\n\020ExchangeRateList\022$\n\rexchan" +
      "ge_rate\030\001 \003(\0132\r.ExchangeRateBE\n0com.dsum" +
      "tsov.mapstruct.protobuf.example.protobuf" +
      "B\021ExchangeRateProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.getDescriptor(),
        });
    internal_static_ExchangeRate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExchangeRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExchangeRate_descriptor,
        new java.lang.String[] { "BasicCurrency", "TargetCurrency", "Rate", });
    internal_static_ExchangeRateList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ExchangeRateList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExchangeRateList_descriptor,
        new java.lang.String[] { "ExchangeRate", });
    com.dsumtsov.mapstruct.protobuf.example.protobuf.BDecimalProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
