// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.dsumtsov.mapstruct.protobuf.example.protobuf;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Any body = 1;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.Any body = 1;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>.google.protobuf.Any body = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>.ErrorCode error = 3;</code>
     * @return Whether the error field is set.
     */
    boolean hasError();
    /**
     * <code>.ErrorCode error = 3;</code>
     * @return The error.
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getError();
    /**
     * <code>.ErrorCode error = 3;</code>
     */
    com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder getErrorOrBuilder();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 26: {
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder subBuilder = null;
              if (error_ != null) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.Any body_;
    /**
     * <code>.google.protobuf.Any body = 1;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.Any body = 1;</code>
     * @return The body.
     */
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.Any body = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode error_;
    /**
     * <code>.ErrorCode error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return error_ != null;
    }
    /**
     * <code>.ErrorCode error = 3;</code>
     * @return The error.
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getError() {
      return error_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.getDefaultInstance() : error_;
    }
    /**
     * <code>.ErrorCode error = 3;</code>
     */
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder getErrorOrBuilder() {
      return getError();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (body_ != null) {
        output.writeMessage(1, getBody());
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (error_ != null) {
        output.writeMessage(3, getError());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBody());
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (error_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getError());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response other = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response) obj;

      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (getSuccess()
          != other.getSuccess()) return false;
      if (hasError() != other.hasError()) return false;
      if (hasError()) {
        if (!getError()
            .equals(other.getError())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        success_ = false;

        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          error_ = null;
          errorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response build() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response buildPartial() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response result = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response(this);
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.success_ = success_;
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response other) {
        if (other == com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response.getDefaultInstance()) return this;
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.Any body = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode error_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder> errorBuilder_;
      /**
       * <code>.ErrorCode error = 3;</code>
       * @return Whether the error field is set.
       */
      public boolean hasError() {
        return errorBuilder_ != null || error_ != null;
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       * @return The error.
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public Builder setError(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public Builder setError(
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public Builder mergeError(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode value) {
        if (errorBuilder_ == null) {
          if (error_ != null) {
            error_ =
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          error_ = null;
          errorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder getErrorBuilder() {
        
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.getDefaultInstance() : error_;
        }
      }
      /**
       * <code>.ErrorCode error = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response();
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorCodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorCode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code ErrorCode}
   */
  public  static final class ErrorCode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ErrorCode)
      ErrorCodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorCode.newBuilder() to construct.
    private ErrorCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorCode() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ErrorCode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorCode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_ErrorCode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_ErrorCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode)) {
        return super.equals(obj);
      }
      com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode other = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ErrorCode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorCode)
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_ErrorCode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_ErrorCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.class, com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.Builder.class);
      }

      // Construct using com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.internal_static_ErrorCode_descriptor;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getDefaultInstanceForType() {
        return com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.getDefaultInstance();
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode build() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode buildPartial() {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode result = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode) {
          return mergeFrom((com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode other) {
        if (other == com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ErrorCode)
    }

    // @@protoc_insertion_point(class_scope:ErrorCode)
    private static final com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode();
    }

    public static com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorCode>
        PARSER = new com.google.protobuf.AbstractParser<ErrorCode>() {
      @java.lang.Override
      public ErrorCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorCode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorCode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorCode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dsumtsov.mapstruct.protobuf.example.protobuf.ResponseProto.ErrorCode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorCode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\032\031google/protobuf/any.pr" +
      "oto\"Z\n\010Response\022\"\n\004body\030\001 \001(\0132\024.google.p" +
      "rotobuf.Any\022\017\n\007success\030\002 \001(\010\022\031\n\005error\030\003 " +
      "\001(\0132\n.ErrorCode\"*\n\tErrorCode\022\014\n\004code\030\001 \001" +
      "(\005\022\017\n\007message\030\002 \001(\tBA\n0com.dsumtsov.maps" +
      "truct.protobuf.example.protobufB\rRespons" +
      "eProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Body", "Success", "Error", });
    internal_static_ErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorCode_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
